on: [push, pull_request]
name: Build
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Install Packages
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y build-essential
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build
      run: |
        go build ./...
