name: ci
on: [push, pull_request]
jobs:
  test-build:
    strategy:
      matrix:
        go-version: [1.17.x, 1.16.x, 1.15.x, 1.14.x, 1.13.x, 1.12.x]
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Test
      run: go test -race -v -timeout 2m ./...
    - name: Build lib
      run: go build
    - name: Build cmd
      run: go build
      working-directory: ./cmd/gotail
